#MATCH CONFIGS
BUILD_AI_ONLY_PLAY = True
BUILD_OUTPUT_DATA_ON = True

#AI Configs
AI_MAX_DEPTH = 2
AI_NUM_OF_BEST_MOVES_CONSIDERED = 4
AI_WAIT_SPEED = 0
AI_GAME_MAX_MOVES = 60
AI_SCORE_SKEW_AMOUNT = 0

